# Generated by Django 5.2.7 on 2025-10-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_product_category_alter_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
